version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    steps:
      - checkout

      - restore_cache:
        keys:
          - ifrcgo-infrastructure-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          key: ifrcgo-infrastructure-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Validate Deployment
          command: yarn validate

      - run:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                yarn deploy
              else
                echo "Skipping deployment"
              fi
